/// كتالوج الخدمات التعاقدية.
///
/// A port of the descriptive half of `src/lib/services.ts`. It carries what a
/// service *is* — its unit, which side of production it serves, and how its
/// billable quantity is derived — and deliberately not what it costs, because
/// prices belong to individual providers and live in the database.
///
/// Duplicated rather than fetched for the same reason agronomy.dart is: someone
/// deciding whether to hire a drone survey is often standing in the field with
/// no signal, and a catalogue that needs a connection is no catalogue for them.
/// The cost of duplication is drift, and `test/services_catalogue_test.dart`
/// pins the two copies together so a change on either side fails the build
/// rather than quietly telling two users two different things.
library;

enum ProductionKind { plant, livestock, both }

enum QuantityBasis { feddans, waterM3, head, months, fixed }

class ServiceDefinition {
  const ServiceDefinition({
    required this.key,
    required this.name,
    required this.kindLabel,
    required this.unitLabel,
    required this.production,
    required this.basis,
    required this.isPrecondition,
    required this.note,
  });

  final String key;
  final String name;
  final String kindLabel;
  final String unitLabel;
  final ProductionKind production;
  final QuantityBasis basis;

  /// True for work that must be finished before anything in the field starts.
  /// A refused permit ends a project where a late survey only delays one, so
  /// these are shown first — the same order the web app schedules them in.
  final bool isPrecondition;

  final String note;
}

const List<ServiceDefinition> serviceCatalogue = [
  // GENERATED from src/lib/services.ts — do not hand-edit.
  //
  // Transcribing forty-one services by hand is how a unit or a precondition
  // flag ends up different on one side, which is exactly what the parity test
  // exists to catch. Regenerate instead: dump the web catalogue and paste the
  // result here, then regenerate the fingerprints in the test alongside it.
  ServiceDefinition(
    key: "contract_notarization",
    name: "توثيق العقد",
    kindLabel: "التوثيق والتصاريح",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "توثيق قانوني يجعل العقد نافذاً أمام جهة قضائية — وهو ما يحمي الطرفين إن اختلفا لاحقاً.",
  ),
  ServiceDefinition(
    key: "crop_insurance",
    name: "وساطة تأمين زراعي",
    kindLabel: "التأمين وإدارة المخاطر",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "ترتيب وثيقة تأمين قبل بدء الموسم. شرط مسبق لأن وثيقة تُطلب بعد وقوع الضرر لا تغطّيه — والتأمين يقوم مقام الضمانة التي يطلبها المموّل.",
  ),
  ServiceDefinition(
    key: "customs_clearance",
    name: "التخليص الجمركي",
    kindLabel: "التوريد والتخليص",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "تكلفة الإرسالية الواحدة لا تتغيّر بمساحة المشروع، فتُسعَّر بالإرسالية. الرسوم الجمركية نفسها تُدفع للدولة لا للمخلّص.",
  ),
  ServiceDefinition(
    key: "feasibility_study",
    name: "دراسة جدوى لمرحلة",
    kindLabel: "مكتب هندسة زراعية",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "دراسة لكل مرحلة، تسبق التعاقد عليها.",
  ),
  ServiceDefinition(
    key: "land_permit",
    name: "تصريح استخدام الأرض",
    kindLabel: "التوثيق والتصاريح",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "يُستخرَج مرة للمشروع لا لكل فدان، فيُسعَّر مقطوعية. بدونه لا يبدأ عمل ميداني أصلاً.",
  ),
  ServiceDefinition(
    key: "local_clearance",
    name: "إجراءات المحلية والإدارة الأهلية",
    kindLabel: "التوثيق والتصاريح",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "موافقات المحلية والإدارة الأهلية في الريف — تختلف من ولاية لأخرى، ومعرفة المسار المحلي هي الخدمة نفسها.",
  ),
  ServiceDefinition(
    key: "machinery_procurement",
    name: "وساطة شراء أو استيراد آلية",
    kindLabel: "التوريد والتخليص",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "أتعاب الوساطة والإجراءات فقط. ثمن الآلية نفسها أصل رأسمالي يتجاوز الموسم ولا يُدرَج في عقد خدمات.",
  ),
  ServiceDefinition(
    key: "water_permit",
    name: "تصريح استخدام المياه",
    kindLabel: "التوثيق والتصاريح",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: true,
    note: "سحب المياه من النيل أو الآبار يحتاج تصريحاً مستقلاً عن تصريح الأرض.",
  ),
  ServiceDefinition(
    key: "cold_storage",
    name: "تخزين مبرّد",
    kindLabel: "التجفيف والتخزين",
    unitLabel: "شهر",
    production: ProductionKind.both,
    basis: QuantityBasis.months,
    isPrecondition: false,
    note: "للخضر والألبان واللحوم. يُسعَّر بالشهر لأن التكلفة تشغيلية مستمرة لا حدث واحد.",
  ),
  ServiceDefinition(
    key: "crop_protection",
    name: "مكافحة",
    kindLabel: "الإرشاد ونقل المعرفة",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "الرش يقاس بالمساحة المعالَجة.",
  ),
  ServiceDefinition(
    key: "drone_survey",
    name: "مسح ورفع مساحي بالدرون",
    kindLabel: "خدمات الطائرات المسيّرة",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "المساحة الممسوحة هي مساحة الموسم نفسها، فالكمية تُشتق من الفدادين لا تُقدَّر.",
  ),
  ServiceDefinition(
    key: "drying",
    name: "تجفيف",
    kindLabel: "التجفيف والتخزين",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "الرطوبة هي ما يفسد الحبوب في المخزن — التجفيف قبل التخزين لا بعده، وإلا حفظ المخزنُ المشكلةَ لا المحصول.",
  ),
  ServiceDefinition(
    key: "extension_visit",
    name: "زيارة إرشادية",
    kindLabel: "الإرشاد ونقل المعرفة",
    unitLabel: "زيارة",
    production: ProductionKind.both,
    basis: QuantityBasis.months,
    isPrecondition: false,
    note: "زيارة شهرية طوال دورة الإنتاج — تقليل المخاطر يحتاج انتظاماً لا زيارة واحدة.",
  ),
  ServiceDefinition(
    key: "feed_plan",
    name: "برنامج تغذية",
    kindLabel: "الإرشاد ونقل المعرفة",
    unitLabel: "رأس",
    production: ProductionKind.livestock,
    basis: QuantityBasis.head,
    isPrecondition: false,
    note: "العلف هو ما يقابل الماء في الإنتاج النباتي: أكبر بند في الميزانية، ويقاس بالرأس.",
  ),
  ServiceDefinition(
    key: "fertigation",
    name: "تسميد",
    kindLabel: "الإرشاد ونقل المعرفة",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "تقاس بالمساحة؛ الجرعة تتبع تحليل التربة.",
  ),
  ServiceDefinition(
    key: "fire_protection",
    name: "الوقاية من الحرائق ومكافحتها",
    kindLabel: "الحماية والأمن",
    unitLabel: "فدان",
    production: ProductionKind.both,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "خطوط نار ومعدات إطفاء وتدريب. الحريق في محصول ناضج يمحو موسماً كاملاً في ساعة.",
  ),
  ServiceDefinition(
    key: "flood_protection",
    name: "الحماية من السيول والفيضان",
    kindLabel: "مكتب هندسة زراعية",
    unitLabel: "فدان",
    production: ProductionKind.both,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "تروس وقنوات تصريف تُبنى قبل الموسم لا أثناءه — والسيل غير المتوقّع موسمياً هو بالضبط ما لا يمهل لبنائها.",
  ),
  ServiceDefinition(
    key: "harvest_service",
    name: "حصاد",
    kindLabel: "الميكنة وإعداد الأرض",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "تقاس بالمساحة المحصودة.",
  ),
  ServiceDefinition(
    key: "haulage",
    name: "ترحيل المحصول",
    kindLabel: "النقل والتخزين",
    unitLabel: "فدان",
    production: ProductionKind.both,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "من الحقل إلى المخزن أو السوق. يقاس بالمساحة لأن الكمية تتبعها؛ والمسافة تدخل في السعر لا في الكمية.",
  ),
  ServiceDefinition(
    key: "herd_health",
    name: "متابعة صحة القطيع",
    kindLabel: "الخدمات البيطرية",
    unitLabel: "زيارة",
    production: ProductionKind.livestock,
    basis: QuantityBasis.months,
    isPrecondition: false,
    note: "متابعة دورية شهرية طوال الدورة.",
  ),
  ServiceDefinition(
    key: "hermetic_storage",
    name: "تخزين محكم",
    kindLabel: "التجفيف والتخزين",
    unitLabel: "شهر",
    production: ProductionKind.plant,
    basis: QuantityBasis.months,
    isPrecondition: false,
    note: "أكياس أو صوامع محكمة تخنق الحشرات بلا مبيد. موثّق أنها تخفض الفاقد من أكثر من ٣٠٪ إلى أقل من ٢٪ — أعلى عائد إلى تكلفة في الكتالوج كله.",
  ),
  ServiceDefinition(
    key: "irrigation_design",
    name: "تصميم شبكة ري",
    kindLabel: "مكتب هندسة زراعية",
    unitLabel: "مقطوعية",
    production: ProductionKind.plant,
    basis: QuantityBasis.fixed,
    isPrecondition: false,
    note: "تصميم واحد للمشروع مهما اتّسع؛ التنفيذ هو ما يتوسّع لا التصميم.",
  ),
  ServiceDefinition(
    key: "irrigation_install",
    name: "تنفيذ شبكة ري",
    kindLabel: "الري الحديث",
    unitLabel: "م³",
    production: ProductionKind.plant,
    basis: QuantityBasis.waterM3,
    isPrecondition: false,
    note: "الشبكة تُحجَّم بالطلب المائي الموسمي المحسوب بمعادلة FAO-56، لا بالمساحة وحدها — فدان بالتنقيط غير فدان بالغمر.",
  ),
  ServiceDefinition(
    key: "land_clearing",
    name: "إزالة وتنظيف",
    kindLabel: "الميكنة وإعداد الأرض",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "عمل ميكانيكي يقاس بالمساحة مباشرة.",
  ),
  ServiceDefinition(
    key: "land_leveling",
    name: "تسوية بالليزر",
    kindLabel: "الميكنة وإعداد الأرض",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "التسوية شرط كفاءة الري؛ تقاس بالمساحة.",
  ),
  ServiceDefinition(
    key: "locust_response",
    name: "الاستجابة لأسراب الجراد",
    kindLabel: "الحماية والأمن",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "استجابة طارئة لا مرحلة مجدوَلة: سرب بمساحة كيلومتر مربع يأكل في يوم ما يأكله ٣٥ ألف إنسان، فالتعاقد على الجاهزية لا على موعد.",
  ),
  ServiceDefinition(
    key: "machinery_maintenance",
    name: "صيانة الآليات",
    kindLabel: "الميكنة وإعداد الأرض",
    unitLabel: "شهر",
    production: ProductionKind.both,
    basis: QuantityBasis.months,
    isPrecondition: false,
    note: "برنامج صيانة دورية بالشهر. الجرار الذي يتعطّل في ذروة الحصاد يكلّف المحصول لا قطعة الغيار.",
  ),
  ServiceDefinition(
    key: "machinery_rental",
    name: "تأجير آلية بمشغّل",
    kindLabel: "الميكنة وإعداد الأرض",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "استئجار جرار أو حصادة مع مشغّلها — عمل ميداني يقاس بالمساحة، لا إجراء إداري.",
  ),
  ServiceDefinition(
    key: "mechanized_planting",
    name: "زراعة ميكانيكية",
    kindLabel: "الميكنة وإعداد الأرض",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "تقاس بالمساحة المزروعة.",
  ),
  ServiceDefinition(
    key: "perimeter_fencing",
    name: "التسوير والحماية",
    kindLabel: "الحماية والأمن",
    unitLabel: "فدان",
    production: ProductionKind.both,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "السياج يمنع السطو ودخول الحيوان السائب معاً. يقاس بالمساحة تقريباً، والمحيط الفعلي يدخل في السعر.",
  ),
  ServiceDefinition(
    key: "preharvest_assessment",
    name: "تقدير المحصول قبل الحصاد",
    kindLabel: "مكتب هندسة زراعية",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "تقدير الكمية المتوقّعة يحدّد حجم النقل والتخزين المطلوب — والتقدير الخاطئ هنا يعني محصولاً ينتظر في العراء.",
  ),
  ServiceDefinition(
    key: "rodent_control",
    name: "مكافحة القوارض",
    kindLabel: "الحماية والأمن",
    unitLabel: "فدان",
    production: ProductionKind.both,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "خطر على الحقل والمخزن معاً — والمخزن أخطر، لأن الفاقد فيه يقع بعد دفع كل تكاليف الإنتاج.",
  ),
  ServiceDefinition(
    key: "site_guarding",
    name: "حراسة الموقع",
    kindLabel: "الحماية والأمن",
    unitLabel: "شهر",
    production: ProductionKind.both,
    basis: QuantityBasis.months,
    isPrecondition: false,
    note: "حراسة بالشهر طوال الدورة — تكلفة مستمرة لا حدث واحد، وتُدرَج في الميزانية بهذه الصفة.",
  ),
  ServiceDefinition(
    key: "soil_conservation",
    name: "صيانة التربة",
    kindLabel: "مكتب هندسة زراعية",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "مصدّات ومدرّجات وحرث كنتوري ضد الانجراف. إنفاق موسم يحمي أصلاً يخدم مواسم — والأرض المنجرفة لا تُستعاد بموسم.",
  ),
  ServiceDefinition(
    key: "soil_test",
    name: "تحليل تربة",
    kindLabel: "تحاليل التربة والمياه",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: false,
    note: "عدد العيّنات لا يتناسب طردياً مع المساحة؛ يُتعاقد عليه مقطوعية للموسم.",
  ),
  ServiceDefinition(
    key: "threshing_cleaning",
    name: "دراس وتنظيف",
    kindLabel: "الميكنة وإعداد الأرض",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "أول خطوة بعد الحصاد مباشرة، وتقاس بالمساحة المحصودة.",
  ),
  ServiceDefinition(
    key: "topo_survey",
    name: "رفع طوبوغرافي",
    kindLabel: "مكتب هندسة زراعية",
    unitLabel: "فدان",
    production: ProductionKind.plant,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "يسبق التسوية ويحدّد ميولها؛ يقاس بالمساحة.",
  ),
  ServiceDefinition(
    key: "transport",
    name: "نقل",
    kindLabel: "النقل والتخزين",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: false,
    note: "يُسعَّر بالرحلة حسب المسافة؛ مقطوعية في العقد.",
  ),
  ServiceDefinition(
    key: "vet_program",
    name: "برنامج بيطري",
    kindLabel: "الخدمات البيطرية",
    unitLabel: "رأس",
    production: ProductionKind.livestock,
    basis: QuantityBasis.head,
    isPrecondition: false,
    note: "التحصين والعلاج يقاسان بالرأس.",
  ),
  ServiceDefinition(
    key: "water_test",
    name: "تحليل مياه",
    kindLabel: "تحاليل التربة والمياه",
    unitLabel: "مقطوعية",
    production: ProductionKind.both,
    basis: QuantityBasis.fixed,
    isPrecondition: false,
    note: "عيّنة من المصدر تكفي الموسم ما لم يتغيّر المصدر.",
  ),
  ServiceDefinition(
    key: "windbreak",
    name: "مصدّات رياح",
    kindLabel: "مكتب هندسة زراعية",
    unitLabel: "فدان",
    production: ProductionKind.both,
    basis: QuantityBasis.feddans,
    isPrecondition: false,
    note: "أحزمة شجرية تقلّل زحف الرمال والبخر معاً — تخدم التربة والاحتياج المائي في آن.",
  ),
];

/// How the billable quantity is described to a reader, per basis.
const Map<QuantityBasis, String> basisLabel = {
  QuantityBasis.feddans: 'يُحسب من مساحة الموسم',
  QuantityBasis.waterM3: 'يُحسب من الاحتياج المائي (FAO-56)',
  QuantityBasis.head: 'يُحسب من عدد الرؤوس',
  QuantityBasis.months: 'يُحسب من طول الدورة',
  QuantityBasis.fixed: 'مقطوعية للموسم',
};
